### ISSUE TITLE
One more <librcs.h> to replace

### ISSUE THREAD

**Issue by NWJeff** [rileym65/Elf-Emulator#1]
https://github.com/rileym65/Elf-Emulator/blob/78f190b9991b5c70ed9f9ba15c6629149e71cec2/toggle.c#L11

There is one more <librcs.h> that needs to be replaced with "librcs.h" in the toggle.c source file.

Thanks!

**Comment by rileym65** [comment]
Thank you very much!  Next time I get into that code I will fix that.
    Mike

________________________________
